#!/bin/bash
set -e

function install()
{
	local NAME=$1
	local HUB=${2:-$DEFAULT_HUB}
	local REPO="https://github.com/$HUB/$NAME.git"
	local VERSION=${3:-$DEFAULT_VERSION}

	# Clone
	if [ ! -d "$PROJECTS/$1" ]; then
		cd "$PROJECTS"
		git clone "$REPO"
	fi

	cd "$PROJECTS/$NAME"

	# Checkout and update
	if has-branch "$VERSION-maint"; then
		echo "Checkout out branch $VERSION-maint"
		git checkout "$VERSION-maint"
		git pull
	elif has-tag "$VERSION"; then
		echo "Checking out tag $VERSION"
		git checkout "$VERSION"
	elif has-branch "$VERSION"; then
		echo "Checking out branch $VERSION"
		git checkout "$VERSION"
	else
		echo "Checking out master"
		git checkout master
		git pull
	fi

	# Setup
	if [ -f "$PROJECTS/$1/setup.py" ]; then
		cd "$PROJECTS/$1"
		python setup.py install
	fi
}

HERE=$(dirname "$(readlink -f "$0")")

. "$HERE/cloudify-config"
. "$HERE/util"

# Install operating system and Python dependencies

sudo apt install python-setuptools python-dev libyaml-dev
sudo easy_install --upgrade pip
sudo pip install --upgrade virtualenv

# virtualenv

if [ ! -d "$VIRTUALENV" ]; then
	virtualenv "$VIRTUALENV"
fi

. "$VIRTUALENV/bin/activate"

# Install Cloudify

mkdir -p "$PROJECTS"
 
install cloudify-dsl-parser
install cloudify-rest-client cloudify-cosmo
install cloudify-plugins-common
install cloudify-script-plugin cloudify-cosmo "$SCRIPT_PLUGIN_VERSION"
install cloudify-cli

install cloudify-manager-blueprints
install cloudify-nodecellar-example GigaSpaces-ProfessionalServices add-static-ip-blueprint

# cfy

cd "$HERE"
set +e
cfy init -r
set -e
