#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")

. "$HERE/cloudify-config"
. "$HERE/util"

# Install operating system dependencies
sudo apt install vagrant sshpass

chmod 400 "$HERE/rsa"

cd "$HERE"

vagrant up

setup-manager "$NETWORK.100"

for I in $(seq 1 "$NODE_COUNT"); do
	setup-node "$NETWORK.$(( 100 + $I ))"
done
