#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")

. "$HERE/cloudify-config"
. "$VIRTUALENV/bin/activate"

#cd "$HERE"

cfy use -t "$NETWORK.100"

cfy blueprints upload \
	-b nodecellar \
	-p "$PROJECTS/cloudify-nodecellar-example/simple-blueprint.yaml"

cfy deployments create \
	-d nodecellar \
	-b nodecellar \
	-i "$HERE/nodecellar/nodecellar-simple-inputs.yaml"

cfy executions start \
	-w install \
	-d nodecellar
